// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmnMXAE2SdPy7fyW17z9jtlHg4KQe1aqQ',
    appId: '1:688426555621:web:ed391f367ab78aa305dc0c',
    messagingSenderId: '688426555621',
    projectId: 'dpchat-e7694',
    authDomain: 'dpchat-e7694.firebaseapp.com',
    storageBucket: 'dpchat-e7694.appspot.com',
    measurementId: 'G-9R9NBQWDF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwM2TkYHLjg0cJ74g2GjdA8USvK9BoTrI',
    appId: '1:688426555621:android:e36b10af6ad258f705dc0c',
    messagingSenderId: '688426555621',
    projectId: 'dpchat-e7694',
    storageBucket: 'dpchat-e7694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkQF6dLN-s78-jvVtr45pTd4slbFaLN8s',
    appId: '1:688426555621:ios:1bd18294c81749d305dc0c',
    messagingSenderId: '688426555621',
    projectId: 'dpchat-e7694',
    storageBucket: 'dpchat-e7694.appspot.com',
    iosClientId: '688426555621-avma9t6p52pj2gbv4o5sn4816m6gjivr.apps.googleusercontent.com',
    iosBundleId: 'com.shekhawatdp.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkQF6dLN-s78-jvVtr45pTd4slbFaLN8s',
    appId: '1:688426555621:ios:12b818c437eafccb05dc0c',
    messagingSenderId: '688426555621',
    projectId: 'dpchat-e7694',
    storageBucket: 'dpchat-e7694.appspot.com',
    iosClientId: '688426555621-1nacmdm2fecte6453fif6c4akr2l715n.apps.googleusercontent.com',
    iosBundleId: 'com.shekhawatdp.flashChat.RunnerTests',
  );
}
